version: '3'
services:
  app1-cont:
    build:
      context: /root/Nginx-reverse-proxy-sandbox/flask-nginx/app1
      dockerfile: Dockerfile 
    image: app1-img:1
  
    ports:
      - '5001:5000'
    container_name: app1-cont
    networks:
      - my_network
    volumes:
      - app1_volume:/app1-dir

  app2-cont:
    build:
      context: /root/Nginx-reverse-proxy-sandbox/flask-nginx/app2 
      dockerfile: Dockerfile  
    image: app2-img:1 
    ports:
      - '5002:5000'
    container_name: app2-cont
    networks:
      - my_network
    volumes:
      - app2_volume:/app2-dir

  nginx-cont:
    image: nginx:latest  
    container_name: nginx-cont
    ports:
      - '80:80'
    networks:
      - my_network
    volumes:
      - /root/Nginx-reverse-proxy-sandbox/nginx.conf:/etc/nginx/nginx.conf

networks:
  my_network:
    driver: bridge
    name: my_network

volumes:
  app1_volume:
    name: app1_volume
  app2_volume:
    name: app2_volume
